HyperIoT-Labs/HyperIoT-UI

projects/widgets/src/lib/dashboard/dynamic-widget/dynamic-widget.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.html
- fixed file field options visibility in widget configurations
- fixed "unavailable widget" for histogram-chart and gauge-chart
=> Widget settings and unavailable widgets fix

projects/widgets/src/lib/base/base-widget/model/widget.model.ts, projects/widgets/src/lib/dashboard/dashboard.module.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/defibrillator-settings/defibrillator-settings.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/defibrillator-settings/defibrillator-settings.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/defibrillator-settings/defibrillator-settings.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/defibrillator-settings/defibrillator-settings.model.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-fields-select/packet-fields-select.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-fields-select/packet-fields-select.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.ts, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.html, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.scss, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.ts
Defibrillator settings:
- introduced min, max, unit for defibrillators value
- removed visualization type
- new ui
Defibrillator widget:
- new **summary** visualization
- defibrillator show min, max, unit values when available
- defibrillator parameters colors now work correctly
- defibrillator parameters in standard view are now aligned and resized based on standard charts
- switch visualization implemented in full screen
Note: This PR makes old defibrillator widget configurations non-functional, therefore the defibrillator widgets need to be reconfigured
=> Defibrillator widget rework - defibrillator summary

src/app/pages/projects/project-forms/packet-fields-form/packet-fields-form.component.html, src/app/pages/projects/project-forms/packet-fields-form/packet-fields-form.component.scss, src/app/pages/projects/project-forms/packet-fields-form/packet-fields-form.component.ts, src/locale/translations.it.xlf, src/locale/translations.xlf
hpacketField of type Object cannot be of multiplicity array or matrix fix
=> hpacketField type multiplicity form fix

projects/components/src/lib/hyt-select-template/hyt-select-template.component.html, projects/widgets/src/lib/base/base-widget/base-widget.component.ts, projects/widgets/src/lib/base/base-widget/model/widget.model.ts, projects/widgets/src/lib/dashboard/dashboard.module.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.ts, projects/widgets/src/lib/widget/gauge-chart/gauge-chart.component.ts, projects/widgets/src/lib/widget/sensor-value/sensor-value.component.css, projects/widgets/src/lib/widget/sensor-value/sensor-value.component.html, projects/widgets/src/lib/widget/sensor-value/sensor-value.component.ts, src/locale/translations.it.xlf, src/locale/translations.xlf
This PR includes the following updates:
- Field properties in widget settings are now grouped by field
- Widget configuration update for unit conversion compatibility
- sensor-value, gauge-chart alias label fix
=> widget configuration ui rework

README.md, src/app/components/notificationbar/notificationbar.component.html, src/locale/translations.it.xlf, src/locale/translations.xlf
- Incorrect translation removed
- Included explanation to resolve localized build error
=> i18n error fix

projects/components/src/lib/hyt-dialog/base-dialog/model/dialog-model.ts, projects/components/src/lib/hyt-dialog/confirm-dialog/confirm-dialog.component.html, projects/components/src/lib/hyt-dialog/confirm-dialog/confirm-dialog.component.scss, projects/components/src/lib/hyt-dialog/confirm-dialog/confirm-dialog.component.ts, projects/components/src/lib/hyt-dialog/confirm-dialog/confirm-dialog.service.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/bodymap-settings/bodymap-settings.component.ts, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts, src/locale/translations.it.xlf, src/locale/translations.xlf
- added dismissable option to confirm-dialog
- added confirmation on widget remove
=> widget remove action confirm

projects/widgets/src/lib/dashboard/dashboard.component.html, projects/widgets/src/lib/dashboard/dashboard.component.ts
In there are no dashboards, the toolbar will now be hidden.
=> Dashboard page: update behavior in case of no dashboards

projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts
fix packet reading regression introduced by d4a06c9
=> dashboard: fix alarms events toast message

projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.html, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts, projects/widgets/src/lib/widget/common-toolbar/common-toolbar.component.html, projects/widgets/src/lib/widget/common-toolbar/common-toolbar.component.scss, projects/widgets/src/lib/widget/error-table/error-table.component.html, projects/widgets/src/lib/widget/event-table/event-table.component.html, projects/widgets/src/lib/widget/events-log/events-log.component.html
- show settings for events-log widget, error-table widget and event-table widget
- widget toolbar: update close icon position to the right.
- widget toolbar: drag handle on full toolbar
- widget toolbar: drag button removed
=> Widget update

projects/widgets/src/lib/base/base-widget-template/base-widget-template.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/time-chart-settings/time-chart-settings.component.ts, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.html, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.ts, projects/widgets/src/lib/widget/ecg/ecg.component.html, projects/widgets/src/lib/widget/ecg/ecg.component.ts, projects/widgets/src/lib/widget/gauge-chart/gauge-chart.component.html, projects/widgets/src/lib/widget/gauge-chart/gauge-chart.component.ts, projects/widgets/src/lib/widget/histogram-chart/histogram-chart.component.ts, projects/widgets/src/lib/widget/line-chart/line-chart.component.ts, projects/widgets/src/lib/widget/sensor-value/sensor-value.component.css
- dashboard widgets resize
- widget line-chart update interval reduced to 100ms
=> Dashboard widgets resize

projects/components/src/lib/hyt-infinite-scrolling-table/hyt-infinite-scrolling-table.component.css, projects/components/src/lib/hyt-lazy-pagination-table/hyt-lazy-pagination-table.component.css, projects/widgets/src/lib/dashboard/widget-settings-dialog/algorithm-settings/algorithm-select/algorithm-select.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/algorithm-settings/algorithm-select/algorithm-select.component.scss, projects/widgets/src/lib/dashboard/widget-settings-dialog/algorithm-settings/algorithm-select/algorithm-select.component.ts, projects/widgets/src/lib/widget/algorithm-table/algorithm-table.component.ts, src/app/components/topbar/topbar.component.scss
- algorithm table output fiedls settings
- algorithm table reset on settings change
- table header height fix
=> Algorithm table improved

src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.html, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts
Fix regarding the post and update of alarm's events and fixed bug that duplicated the tags in the event
=> HYIOTPT-897 fixed event list post and update

src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.html, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.scss, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts
fixed events creation, update and deletion and tagsids retrieval
=> Alarms fix hyiotpt 897

projects/core/src/lib/hyperiot-base/offline-data-service/OfflineDataChannelController.ts, projects/core/src/lib/hyperiot-base/offline-data-service/offline-data.service.ts, projects/widgets/src/lib/dashboard/dashboard.component.ts, projects/widgets/src/lib/dashboard/timeline/timeline.component.ts
- add/modify/delete actions on a widget now updates only the specific widget and no longer affects all widgets
- Improved logic for timeline updates, now making fewer data requests
=> Offline dashboard independent widgets logic

projects/components/src/lib/hyt-chatbot/hyt-chatbot.component.ts, src/app/app.component.html, src/environments/environment.prod.ts, src/environments/environment.ts
Add parameter to chatbot components
Fix comment into environment file.
=> Cca fix chatbot parametrize

projects/core/src/lib/hyperiot-client/h-packet-client/api-module/api/hpackets.service.ts, projects/widgets/src/lib/widget/algorithm-table/algorithm-table.component.ts
**Added new grouping view on dashboard algorithm table**
=> Added new grouping view on dashboard algorithm table 

projects/core/src/lib/hyperiot-base/offline-data-service/offline-data.service.ts, projects/widgets/src/lib/widget/line-chart/line-chart.component.html, projects/widgets/src/lib/widget/line-chart/line-chart.component.ts
- When clicked, doesn't load data anymore. Now it's fixed
- Add isRangeLoaded to the single dataChannel cuz when there was more than one linechart and one of them was already loaded, every widget stop load data anymore.
- Add loader when the function is called
=> Fix reset button load & fit to timeline

projects/core/src/lib/hyperiot-base/offline-data-service/offline-data.service.ts, projects/widgets/src/lib/dashboard/dashboard.component.ts, projects/widgets/src/lib/dashboard/services/dashboard-event.model.ts, projects/widgets/src/lib/dashboard/services/dashboard-event.service.ts, projects/widgets/src/lib/dashboard/timeline/time-axis/time-axis.component.ts, projects/widgets/src/lib/default-widget/default-widget.component.html, projects/widgets/src/lib/widget/algorithm-table/algorithm-table.component.html, projects/widgets/src/lib/widget/bodymap/bodymap.component.html, projects/widgets/src/lib/widget/common-toolbar/common-toolbar.component.ts, projects/widgets/src/lib/widget/data-simulator/data-simulator.component.html, projects/widgets/src/lib/widget/data-simulator/data-simulator.component.ts, projects/widgets/src/lib/widget/defibrillator/defibrillator.component.html, projects/widgets/src/lib/widget/dynamic-label-value-widget/dynamic-label-value-widget.component.html, projects/widgets/src/lib/widget/ecg/ecg.component.html, projects/widgets/src/lib/widget/error-table/error-table.component.html, projects/widgets/src/lib/widget/event-table/event-table.component.html, projects/widgets/src/lib/widget/events-log/events-log.component.html, projects/widgets/src/lib/widget/events-log/events-log.component.ts, projects/widgets/src/lib/widget/gauge-chart/gauge-chart.component.html, projects/widgets/src/lib/widget/histogram-chart/histogram-chart.component.html, projects/widgets/src/lib/widget/hpacket-table/hpacket-table.component.html, projects/widgets/src/lib/widget/line-chart/line-chart.component.html, projects/widgets/src/lib/widget/line-chart/line-chart.component.ts, projects/widgets/src/lib/widget/multi-status-widget/multi-status-widget.component.html, projects/widgets/src/lib/widget/production-target/production-target.component.html, projects/widgets/src/lib/widget/sensor-value/sensor-value.component.html, src/app/pages/projects/project-detail/generic-summary-list/generic-summary-list.component.ts
On the dashboard, i've fix some bug and add some features:
- *ADDED*: DashboardEventService: Emit an event when the timeline or command is trigger
- *FIXED*: After fit to timeline, if the user refresh data show only the first 50 elements. Now it show the same range updated
- *FIXED*: play/pause functionality restored
- *FIXED*: Raw data logger filter for projectId on systemTick event
- *FIXED*: Data simulator is stopped when you stop the dashboard (stop only, not pause)
=> Bugfix on dashboard

projects/widgets/src/lib/dashboard/services/dashboard-event.service.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/data-simulator-settings/data-simulator-settings.component.html, projects/widgets/src/lib/widget/data-simulator/data-simulator.component.ts
- Stop simulator only on stop/run command and not play/pause
- Error when fieldType was undefined in old settings, this functionality was introduced for boolean simulator but break some old setting
=> Data simulator setting broken in old project

src/app/app.component.html, src/app/app.module.ts, src/app/configuration-modules/hyt-routing.module.ts, src/app/constants/httpErrorsDictionary.ts, src/app/interceptors/http-error.interceptor.spec.ts, src/app/interceptors/http-error.interceptor.ts, src/locale/translations.it.xlf, src/locale/translations.xlf
Added an HttpInterceptor to notify the user of any error messages via the hyt-notification-box.
- The interceptor can be excluded from routes using the hyt-routing.module or from individual requests using HttpContext
- You can customize error messages using HttpContext
=> http error interceptor: optionally notify error messages to the user

src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts, src/assets/styles/_main.scss
- Fixed toastr style import 
- Removed additional classes
=> Fixed toastr style (HYIOTPT-1061)

package.json, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts
Fix bug "Waiting for Data": if alert event not exists in alert events  map, the application crashed.
=> Hyiotpt 1073

package.json, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts
Add new action on package.json
Add toastr disableTimeout property (set false for compatibility)
Fix form reset to add new property
=> Fix alarm severity form reset on add(HYIOTPT-1062)

projects/widgets/src/lib/widget/events-log/events-log.component.ts
Update filter for new event data format to filter by project id.
=> Widget data logger update filter for project id

projects/components/src/lib/rule-definition/rule-definition.component.html, projects/components/src/lib/rule-definition/rule-definition.component.ts, src/app/pages/projects/project-detail/project-detail.component.ts, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.html, src/app/pages/projects/project-forms/project-alarms-form/project-alarms-form.component.ts
- if event list is invalid or not compiled, button remains disabled
- Remove debug message into project detail isDisableProjectAlarmsFormComponent function, too much verbose.
=> Fix save severity button: if event list is invalid or not compiled, button remains disabled

src/app/app.component.ts
**Fix double toastr**
The event subscribe now filter when receive more than one identical item (distinctUntilChanged).
=> Fix double toastr: add tap and distinctUntilChanged nella subscribe degli eventi.

projects/components/src/lib/rule-definition/rule-definition.component.ts
=> rule-definition fix

projects/widgets/src/lib/dashboard/dashboard-config.service.ts, projects/widgets/src/lib/dashboard/dashboard.component.html, projects/widgets/src/lib/dashboard/dashboard.component.scss, projects/widgets/src/lib/dashboard/dashboard.component.ts, projects/widgets/src/lib/dashboard/services/dashboard-event.model.ts, projects/widgets/src/lib/dashboard/services/dashboard-event.service.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/packet-select/packet-select.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/time-chart-settings/time-chart-settings.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/time-chart-settings/time-chart-settings.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.html, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.ts, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts, src/app/configuration-modules/hyt-routing.module.ts, src/app/pages/areas/container-area-map/container-area-map.component.ts, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.html, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.scss, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.ts, src/locale/translations.it.xlf, src/locale/translations.xlf
Add device dashboard
Add click function to area contextual menu
Change dashboard device style
Add to device dashboard the area button to return back
=> Device dashboard

src/app/app.component.html, src/app/app.component.ts, src/app/configuration-modules/hyt-routing.module.ts
=> Fix login notification error

projects/core/src/lib/hyperiot-service/hyperiot-alarm-wrapper/hyperiot-alarm-wrapper.service.ts, src/app/components/topbar/account-button/account-button.component.ts, src/app/configuration-modules/hyt-routing.module.ts, src/app/pages/authentication/login/login.component.ts, src/app/services/branding/branding.service.ts, src/app/services/postLogin/post-login.service.spec.ts, src/app/services/postLogin/post-login.service.ts
Added post-login logic to load data after login or authentication check.
=> Post login logic

projects/widgets/src/lib/dashboard/dashboard.component.html
Removed tick message implementation
=> Removed tick message implementation

projects/core/src/lib/hyperiot-base/base-data.service.ts, projects/core/src/lib/hyperiot-base/data.interface.ts, projects/core/src/lib/hyperiot-base/offline-data-service/OfflineDataChannelController.ts, projects/core/src/lib/hyperiot-base/offline-data-service/offline-data.service.ts, projects/widgets/src/lib/data/time-series.ts, projects/widgets/src/lib/widget/hpacket-table/hpacket-table.component.html, projects/widgets/src/lib/widget/hpacket-table/hpacket-table.component.ts, projects/widgets/src/lib/widget/line-chart/line-chart.component.ts
offline widget fullscreen fix
line-chart alias fix
=> Dashboard Widget fix

projects/widgets/src/lib/base/base-widget/base-widget.component.ts, projects/widgets/src/lib/widget/events-log/events-log.component.ts
Fix event-log (row-logger) data stream
=> Fix event-log (row-logger) data stream

projects/widgets/src/lib/base/base-widget/base-widget.component.ts
Fix "double" conversion issue on full-screen mode
=> fix conversion issue

projects/widgets/src/lib/dashboard/dashboard.component.ts, projects/widgets/src/lib/dashboard/widget-settings-dialog/widget-settings-dialog.component.ts, src/app/pages/projects/project-detail/project-detail.component.ts
use selectDefaultProjectsDashboardDataSource on project switch
=> Fix dashboard offline - switch project

projects/components/src/lib/hyt-map/components/leaflet-map/leaflet-map.component.ts, projects/components/src/lib/hyt-map/components/map-device-info/map-device-info.component.html, projects/components/src/lib/hyt-map/components/map-device-info/map-device-info.component.ts, projects/components/src/lib/hyt-map/services/utils.service.ts, projects/components/src/public-api.ts, src/app/pages/projects/project-forms/areas-form/area-map/area-map.component.ts, src/app/pages/projects/project-forms/areas-form/areas-form.component.ts, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.html, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.scss, src/app/pages/projects/project-forms/areas-form/draggable-item/draggable-item.component.ts
BUG: clicking on the icon of a sub-area in the image of an area does not get any results. Instead, it should lead to the selected subarea.
=> fix hyt-draggable-item menu

projects/widgets/src/lib/base/base-widget/model/widget.model.ts, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.html, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.scss, projects/widgets/src/lib/dashboard/widgets-layout/widgets-layout.component.ts
fix the position of the widgets when resizing
=> Dashboard resize
